### ISSUE TITLE
create element <caps>

### ISSUE THREAD

**Issue by pencerw** [3MFConsortium/spec_beamlattice#13]
\<caps> will be a daughter to \<beamlattice> and will contain a list of caps. each cap (name TBD) will have an attribute "radius" (name TBD) and an attribute "vertex". 

...or something ;)

**Comment by pencerw** [comment]
this can be started here: https://github.com/3MFConsortium/spec_beamlattice/tree/2018-enhancements

**Comment by jordig100** [comment]
Dropped by now
