### ISSUE TITLE
Format of TOC is inconsistent

### ISSUE THREAD

**Issue by martinweismann** [3MFConsortium/spec_beamlattice#19]
Please update the TOC to be formatted analogously to
https://github.com/3MFConsortium/spec_core/blob/develop_1.2.4/3MF%20Core%20Specification.md#table-of-contents

https://github.com/3MFConsortium/spec_core/issues/25

**Comment by markforsyth** [comment]
Actually the numbering of the various section and figures is inconsistent throughout the document.

**Comment by jordig100** [comment]
Fixed in 1,1 proposal
