### ISSUE TITLE
transformation of clippingmesh and representationmesh

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/spec_beamlattice#20]
If a beamlattice mesh object is instantiated in a components object, and has a transformation
OR
if a beamlattice mesh object is added to build items with a transformation
then does the transformation apply to the representation mesh and clipping mesh as well?

**Comment by jordig100** [comment]
That's correct. The beam lattices defines a shape, so the transform is applied on that shape. Same for the combination beamlattice and clipping mesh.
