### ISSUE TITLE
Fill rule between meshes and beam lattices

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_beamlattice#24]
The specification states "The triangle mesh geometry MUST be unified with the lattice geometry according to the positive fill rule (for the triangles)." I think I understand this, I assume just like when triangular mesh objects intersect, you have to sort out when a beam intersects another beam or triangular mesh which ares are inside or outside of the volume.

**Comment by jordig100** [comment]
One way to interpret it is that the beamlattice needs to be resolved as creating a single volume, where the content defines a +1 when overlapping to the mesh. Then the fill rule applies.

In any case, it deserves some clarification, since other interpretations could as well be possible.

**Comment by markforsyth** [comment]
Current spec states

> The triangle mesh geometry MUST be unified with the lattice geometry according to the positive fill rule (for the triangles).


Propose to change to
                

> The lattice geometry and any mesh geometry defined in the containing object MUST be unified according to the positive fill rule (as defined in the Core Specification) to resolve any overlapping regions.  This includes overlaps between and within lattices.

**Comment by markforsyth** [comment]
Addressed in v 1.1
