### ISSUE TITLE
Requirement to use clippingmesh ambiguous

### ISSUE THREAD

**Issue by markforsyth** [3MFConsortium/spec_beamlattice#25]
The spec states : -

> The lattice MAY be geometrically clipped against a reference mesh. The clipping mode determines which parts of the lattice define the final geometry.

The correctly indicates the clippingmesh is optional.  However, it does not indicate what a consumer is required to do if a clippingmesh is defined.

Suggest change to something like

> The lattice MAY be geometrically clipped against a reference mesh as defined by the clippingmode and clippingmesh attributes. The clipping mode determines which parts of the lattice define the final geometry.  Consumers SHOULD (or MUST?) clip the beam lattice when a clippingmesh is provided and the clippingmode is not equal to "none".

**Comment by jordig100** [comment]
I agree with the clarification. For the consumers it is a MUST to support the clipping mesh.

**Comment by jordig100** [comment]
Fixed in proposal 1.1
