### ISSUE TITLE
Representation mesh containing only triangles

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_beamlattice#27]
Clarify that the representation mesh MUST only contain a triangle mesh, and not beamlattices, slices, etc.

**Comment by JimZuber** [comment]
Assuming the spec will be updated to limit representationmesh to triangular mesh, would the expected behavior be to ignore the representationmesh if it contains a beam lattice or raise an exception and stop processing the 3MF file?

**Comment by jordig100** [comment]
Duplicated of #21 and clarified in proposal 1,1
