### ISSUE TITLE
No gradients for beams with basematerial properties.

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_beamlattice#28]
Clarify in the beam element that is P1 or P2 are a basematerial property, either they are equal or then P2 MUST be ignored.

**Comment by markforsyth** [comment]
Number of possibilities here

- P1 == P2 then OK 
- P1 != P2 then if neither is a base material OK. If P1 is a base material and P2 isn’t then ignore P2.  If P2 is a base material and P1 isn’t – do we ignore P1?

**Comment by markforsyth** [comment]
Or,

If P1 is a base material P2 MUST be equal to P1 or unspecified. If P1 is not a base material then P2 MUST not be a base material.

**Comment by jordig100** [comment]
Yes, this last one.

**Comment by markforsyth** [comment]
Addressed in v1.1
