### ISSUE TITLE
Require beamlattice or object pid if beam has pid

### ISSUE THREAD

**Issue by JimZuber** [3MFConsortium/spec_beamlattice#29]
In the core specification it states "If this object contains any triangles with assigned materials, the object MUST specify pid and pindex, to act as default values for any triangles with unspecified properties."

However, there is no equivalent statement for a beam that references a pid. As things stand, you could have a beam with a pid, but no pid at the beamlattice or object level.  Should there be an equivalent statement in the beam lattice spec that state "If  this beam lattice contains any beams with assigned materials, the beamlattice or object MUST specify pid and pindex, to act as default values for any beams with unspecified properties"?

**Comment by JimZuber** [comment]
Assuming we do need some default pid if a single beam uses pid, is it ok for the higher level pid to be just beamlattice, with no pid at the object level for triangles?

**Comment by jordig100** [comment]
I think that, similarly to the core spec, if pid is specified at either beam lattices level or beams level, it MUST be specified at object level.

This way we would have:
Default object pid --> optional beamlattices pid --> optional beams pid.

**Comment by markforsyth** [comment]
Propose to add similar language to the core spec for beams.  That is add

> If this beam lattice contains any beams or balls with assigned materials, the object MUST specify pid and pindex, to act as default values for any beam or balls with unspecified properties.

Another possibility could be

> If this beam lattice contains any beams or balls with assigned materials, the beam lattice or object MUST specify pid and pindex, to act as default values for any beam or balls with unspecified properties.

**Comment by jordig100** [comment]
I think that is both beam lattice and object MUST specify pid and pindex.
Needs to be cascaded a default from bottom to up, to be able to override it.

**Comment by markforsyth** [comment]
Addressed in v 1.1
