### ISSUE TITLE
What colors get applied to a clipped beam lattice?

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_beamlattice#31]
The spec doesn't specify what colors show up in the clipped surface.

Proposal is to apply the color, or property, from the clipping mesh.

**Comment by markforsyth** [comment]
Or just apply the beam colour or property. Then the clipped beam ends behave like a cap.

**Comment by jordig100** [comment]
What about an analog definition to the one in Volumetric:

- Volumetric content is always clipped to the surface of the mesh that embedds it. If a property (color or properties) defined at the surface of an object conflicts with the property within the object defined by this extension, a surface layer should be defined with a thickness as small as possible to achieve the surface property on the outside of the object. Outside of this thin surface region, the volumetric property should be applied everywhere within the object.

I think that it makes sense to be able to define a colour in the clipping mesh that "colours" the clipping region.

**Comment by markforsyth** [comment]
Addressed in v 1.1.0
