### ISSUE TITLE
CT_BeamSet schema error

### ISSUE THREAD

**Issue by JimZuber** [3MFConsortium/spec_beamlattice#34]
I  noticed the following error in the schema published in the extension specification for beam lattice. The spec has the following syntax which generates an XML syntax violation....

<xs:complexType name="CT_BeamSet">
    <xs:sequence>
        <xs:element ref="ref" minOccurs="0" maxOccurs=" 2147483647 "/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs=" 2147483647"/>
    </xs:sequence>
    <xs:sequence>
        <xs:element ref="ballref" minOccurs="0" maxOccurs="2147483647"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="2147483647"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="identifier" type="xs:string"/>
    <xs:anyAttribute namespace="##other" processContents="lax"/>
</xs:complexType>

I believe that you cannot have two back to back sequence elements in a complexType.

I think the following syntax achieves the intent without a XML syntax error...

  <xs:complexType name="CT_BeamSet">
    <xs:sequence>
        <xs:element ref="ref" minOccurs="0" maxOccurs=" 2147483647 "/>
        <xs:element ref="ballref" minOccurs="0" maxOccurs="2147483647"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs=" 2147483647 "/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="identifier" type="xs:string"/>
    <xs:anyAttribute namespace="##other" processContents="lax"/>
</xs:complexType>

**Comment by jordig100** [comment]
Fixed in version 1.2.0
