### ISSUE TITLE
Must be object property be defined is properties in beams or balls?

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/spec_beamlattice#36]
Current definition:
_If this beam lattice contains any beam or ball with assigned properties, the beam lattice or object MUST specify pid and pindex, to act as default values for any beam or ball with unspecified properties._

Contradicts the definition in the beamlattices table:

pid | ST_ResourceID | optional |   | Overrides   the object-level pid as default for all beams.
-- | -- | -- | -- | --
pindex | ST_ResourceIndex | optional |   | Overrides   the object-level pindex as default for all beams.

Since if pid/pindex overrides the object default, it implicitelly says that there is a defined default at object level, where the paragrapgh specifies it as optional.

What about a definition as:

_If this beam lattice contains any beam or ball with assigned properties, the object MUST specify pid and pindex, to act as default values for any beamlattices and a beamlattice MIGHT specify pid/pindex to override those defaults for the beams or balls with unspecified properties._

**Comment by markforsyth** [comment]
I am not sure.  Perhaps we just do not need the paragraph at all?    If  one or more beams has properties but nothing is defined at the beam lattice level or object level then the rest of the beams get whatever the printer default is.

**Comment by jordig100** [comment]
Left as no change.
